const WORLD_COUNTRIES = [
  {
    "code": "AF",
    "iso3": "AFG",
    "name": "Afghanistan",
    "capital": "Kabul",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Low income",
    "currency": "AFN",
    "currencyName": "Afghan Afghani",
    "symbol": "؋",
    "latitude": 34.5228,
    "longitude": 69.1761,
    "flag": "🇦🇫"
  },
  {
    "code": "AL",
    "iso3": "ALB",
    "name": "Albania",
    "capital": "Tirane",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "ALL",
    "currencyName": "Albanian Lek",
    "symbol": "L",
    "latitude": 41.3317,
    "longitude": 19.8172,
    "flag": "🇦🇱"
  },
  {
    "code": "DZ",
    "iso3": "DZA",
    "name": "Algeria",
    "capital": "Algiers",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Upper middle income",
    "currency": "DZD",
    "currencyName": "Algerian Dinar",
    "symbol": "د.ج",
    "latitude": 36.7397,
    "longitude": 3.05097,
    "flag": "🇩🇿"
  },
  {
    "code": "AS",
    "iso3": "ASM",
    "name": "American Samoa",
    "capital": "Pago Pago",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": -14.2846,
    "longitude": -170.691,
    "flag": "🇦🇸"
  },
  {
    "code": "AD",
    "iso3": "AND",
    "name": "Andorra",
    "capital": "Andorra la Vella",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 42.5075,
    "longitude": 1.5218,
    "flag": "🇦🇩"
  },
  {
    "code": "AO",
    "iso3": "AGO",
    "name": "Angola",
    "capital": "Luanda",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "AOA",
    "currencyName": "Angolan Kwanza",
    "symbol": "Kz",
    "latitude": -8.81155,
    "longitude": 13.242,
    "flag": "🇦🇴"
  },
  {
    "code": "AG",
    "iso3": "ATG",
    "name": "Antigua and Barbuda",
    "capital": "Saint John's",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "XCD",
    "currencyName": "East Caribbean Dollar",
    "symbol": "$",
    "latitude": 17.1175,
    "longitude": -61.8456,
    "flag": "🇦🇬"
  },
  {
    "code": "AR",
    "iso3": "ARG",
    "name": "Argentina",
    "capital": "Buenos Aires",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "ARS",
    "currencyName": "Argentine Peso",
    "symbol": "$",
    "latitude": -34.6118,
    "longitude": -58.4173,
    "flag": "🇦🇷"
  },
  {
    "code": "AM",
    "iso3": "ARM",
    "name": "Armenia",
    "capital": "Yerevan",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "AMD",
    "currencyName": "Armenian Dram",
    "symbol": "֏",
    "latitude": 40.1596,
    "longitude": 44.509,
    "flag": "🇦🇲"
  },
  {
    "code": "AW",
    "iso3": "ABW",
    "name": "Aruba",
    "capital": "Oranjestad",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 12.5167,
    "longitude": -70.0167,
    "flag": "🇦🇼"
  },
  {
    "code": "AU",
    "iso3": "AUS",
    "name": "Australia",
    "capital": "Canberra",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "AUD",
    "currencyName": "Australian Dollar",
    "symbol": "$",
    "latitude": -35.282,
    "longitude": 149.129,
    "flag": "🇦🇺"
  },
  {
    "code": "AT",
    "iso3": "AUT",
    "name": "Austria",
    "capital": "Vienna",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 48.2201,
    "longitude": 16.3798,
    "flag": "🇦🇹"
  },
  {
    "code": "AZ",
    "iso3": "AZE",
    "name": "Azerbaijan",
    "capital": "Baku",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "AZN",
    "currencyName": "Azerbaijani Manat",
    "symbol": "₼",
    "latitude": 40.3834,
    "longitude": 49.8932,
    "flag": "🇦🇿"
  },
  {
    "code": "BH",
    "iso3": "BHR",
    "name": "Bahrain",
    "capital": "Manama",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "BHD",
    "currencyName": "Bahraini Dinar",
    "symbol": ".د.ب",
    "latitude": 26.1921,
    "longitude": 50.5354,
    "flag": "🇧🇭"
  },
  {
    "code": "BD",
    "iso3": "BGD",
    "name": "Bangladesh",
    "capital": "Dhaka",
    "region": "South Asia",
    "income": "Lower middle income",
    "currency": "BDT",
    "currencyName": "Bangladeshi Taka",
    "symbol": "৳",
    "latitude": 23.7055,
    "longitude": 90.4113,
    "flag": "🇧🇩"
  },
  {
    "code": "BB",
    "iso3": "BRB",
    "name": "Barbados",
    "capital": "Bridgetown",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "BBD",
    "currencyName": "Barbadian Dollar",
    "symbol": "$",
    "latitude": 13.0935,
    "longitude": -59.6105,
    "flag": "🇧🇧"
  },
  {
    "code": "BY",
    "iso3": "BLR",
    "name": "Belarus",
    "capital": "Minsk",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "BYN",
    "currencyName": "Belarusian Ruble",
    "symbol": "Br",
    "latitude": 53.9678,
    "longitude": 27.5766,
    "flag": "🇧🇾"
  },
  {
    "code": "BE",
    "iso3": "BEL",
    "name": "Belgium",
    "capital": "Brussels",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 50.8371,
    "longitude": 4.36761,
    "flag": "🇧🇪"
  },
  {
    "code": "BZ",
    "iso3": "BLZ",
    "name": "Belize",
    "capital": "Belmopan",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "BZD",
    "currencyName": "Belize Dollar",
    "symbol": "$",
    "latitude": 17.2534,
    "longitude": -88.7713,
    "flag": "🇧🇿"
  },
  {
    "code": "BJ",
    "iso3": "BEN",
    "name": "Benin",
    "capital": "Porto-Novo",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 6.4779,
    "longitude": 2.6323,
    "flag": "🇧🇯"
  },
  {
    "code": "BM",
    "iso3": "BMU",
    "name": "Bermuda",
    "capital": "Hamilton",
    "region": "North America",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 32.3293,
    "longitude": -64.706,
    "flag": "🇧🇲"
  },
  {
    "code": "BT",
    "iso3": "BTN",
    "name": "Bhutan",
    "capital": "Thimphu",
    "region": "South Asia",
    "income": "Lower middle income",
    "currency": "BTN",
    "currencyName": "Bhutanese Ngultrum",
    "symbol": "Nu.",
    "latitude": 27.5768,
    "longitude": 89.6177,
    "flag": "🇧🇹"
  },
  {
    "code": "BO",
    "iso3": "BOL",
    "name": "Bolivia",
    "capital": "La Paz",
    "region": "Latin America & Caribbean",
    "income": "Lower middle income",
    "currency": "BOB",
    "currencyName": "Bolivian Boliviano",
    "symbol": "Bs.",
    "latitude": -13.9908,
    "longitude": -66.1936,
    "flag": "🇧🇴"
  },
  {
    "code": "BA",
    "iso3": "BIH",
    "name": "Bosnia and Herzegovina",
    "capital": "Sarajevo",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "BAM",
    "currencyName": "Bosnia and Herzegovina Convertible Mark",
    "symbol": "KM",
    "latitude": 43.8607,
    "longitude": 18.4214,
    "flag": "🇧🇦"
  },
  {
    "code": "BW",
    "iso3": "BWA",
    "name": "Botswana",
    "capital": "Gaborone",
    "region": "Sub-Saharan Africa",
    "income": "Upper middle income",
    "currency": "BWP",
    "currencyName": "Botswana Pula",
    "symbol": "P",
    "latitude": -24.6544,
    "longitude": 25.9201,
    "flag": "🇧🇼"
  },
  {
    "code": "BR",
    "iso3": "BRA",
    "name": "Brazil",
    "capital": "Brasilia",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "BRL",
    "currencyName": "Brazilian Real",
    "symbol": "R$",
    "latitude": -15.7801,
    "longitude": -47.9292,
    "flag": "🇧🇷"
  },
  {
    "code": "VG",
    "iso3": "VGB",
    "name": "British Virgin Islands",
    "capital": "Road Town",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 18.431389,
    "longitude": -64.623056,
    "flag": "🇻🇬"
  },
  {
    "code": "BN",
    "iso3": "BRN",
    "name": "Brunei Darussalam",
    "capital": "Bandar Seri Begawan",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "BND",
    "currencyName": "Brunei Dollar",
    "symbol": "$",
    "latitude": 4.94199,
    "longitude": 114.946,
    "flag": "🇧🇳"
  },
  {
    "code": "BG",
    "iso3": "BGR",
    "name": "Bulgaria",
    "capital": "Sofia",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "BGN",
    "currencyName": "Bulgarian Lev",
    "symbol": "лв",
    "latitude": 42.7105,
    "longitude": 23.3238,
    "flag": "🇧🇬"
  },
  {
    "code": "BF",
    "iso3": "BFA",
    "name": "Burkina Faso",
    "capital": "Ouagadougou",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 12.3605,
    "longitude": -1.53395,
    "flag": "🇧🇫"
  },
  {
    "code": "BI",
    "iso3": "BDI",
    "name": "Burundi",
    "capital": "Bujumbura",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "BIF",
    "currencyName": "Burundian Franc",
    "symbol": "FBu",
    "latitude": -3.3784,
    "longitude": 29.3639,
    "flag": "🇧🇮"
  },
  {
    "code": "CV",
    "iso3": "CPV",
    "name": "Cabo Verde",
    "capital": "Praia",
    "region": "Sub-Saharan Africa",
    "income": "Upper middle income",
    "currency": "CVE",
    "currencyName": "Cape Verdean Escudo",
    "symbol": "Esc",
    "latitude": 14.9218,
    "longitude": -23.5087,
    "flag": "🇨🇻"
  },
  {
    "code": "KH",
    "iso3": "KHM",
    "name": "Cambodia",
    "capital": "Phnom Penh",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "KHR",
    "currencyName": "Cambodian Riel",
    "symbol": "៛",
    "latitude": 11.5556,
    "longitude": 104.874,
    "flag": "🇰🇭"
  },
  {
    "code": "CM",
    "iso3": "CMR",
    "name": "Cameroon",
    "capital": "Yaounde",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "XAF",
    "currencyName": "Central African CFA Franc",
    "symbol": "FCFA",
    "latitude": 3.8721,
    "longitude": 11.5174,
    "flag": "🇨🇲"
  },
  {
    "code": "CA",
    "iso3": "CAN",
    "name": "Canada",
    "capital": "Ottawa",
    "region": "North America",
    "income": "High income",
    "currency": "CAD",
    "currencyName": "Canadian Dollar",
    "symbol": "$",
    "latitude": 45.4215,
    "longitude": -75.6919,
    "flag": "🇨🇦"
  },
  {
    "code": "KY",
    "iso3": "CYM",
    "name": "Cayman Islands",
    "capital": "George Town",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 19.3022,
    "longitude": -81.3857,
    "flag": "🇰🇾"
  },
  {
    "code": "CF",
    "iso3": "CAF",
    "name": "Central African Republic",
    "capital": "Bangui",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "XAF",
    "currencyName": "Central African CFA Franc",
    "symbol": "FCFA",
    "latitude": 5.63056,
    "longitude": 21.6407,
    "flag": "🇨🇫"
  },
  {
    "code": "TD",
    "iso3": "TCD",
    "name": "Chad",
    "capital": "N'Djamena",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "XAF",
    "currencyName": "Central African CFA Franc",
    "symbol": "FCFA",
    "latitude": 12.1048,
    "longitude": 15.0445,
    "flag": "🇹🇩"
  },
  {
    "code": "JG",
    "iso3": "CHI",
    "name": "Channel Islands",
    "capital": "N/A",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": null,
    "longitude": null,
    "flag": "🇯🇬"
  },
  {
    "code": "CL",
    "iso3": "CHL",
    "name": "Chile",
    "capital": "Santiago",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "CLP",
    "currencyName": "Chilean Peso",
    "symbol": "$",
    "latitude": -33.475,
    "longitude": -70.6475,
    "flag": "🇨🇱"
  },
  {
    "code": "CN",
    "iso3": "CHN",
    "name": "China",
    "capital": "Beijing",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "CNY",
    "currencyName": "Chinese Yuan",
    "symbol": "¥",
    "latitude": 40.0495,
    "longitude": 116.286,
    "flag": "🇨🇳"
  },
  {
    "code": "CO",
    "iso3": "COL",
    "name": "Colombia",
    "capital": "Bogota",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "COP",
    "currencyName": "Colombian Peso",
    "symbol": "$",
    "latitude": 4.60987,
    "longitude": -74.082,
    "flag": "🇨🇴"
  },
  {
    "code": "KM",
    "iso3": "COM",
    "name": "Comoros",
    "capital": "Moroni",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "KMF",
    "currencyName": "Comorian Franc",
    "symbol": "CF",
    "latitude": -11.6986,
    "longitude": 43.2418,
    "flag": "🇰🇲"
  },
  {
    "code": "CR",
    "iso3": "CRI",
    "name": "Costa Rica",
    "capital": "San Jose",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "CRC",
    "currencyName": "Costa Rican Colón",
    "symbol": "₡",
    "latitude": 9.63701,
    "longitude": -84.0089,
    "flag": "🇨🇷"
  },
  {
    "code": "CI",
    "iso3": "CIV",
    "name": "Cote d'Ivoire",
    "capital": "Yamoussoukro",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 5.332,
    "longitude": -4.0305,
    "flag": "🇨🇮"
  },
  {
    "code": "HR",
    "iso3": "HRV",
    "name": "Croatia",
    "capital": "Zagreb",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 45.8069,
    "longitude": 15.9614,
    "flag": "🇭🇷"
  },
  {
    "code": "CU",
    "iso3": "CUB",
    "name": "Cuba",
    "capital": "Havana",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "CUP",
    "currencyName": "Cuban Peso",
    "symbol": "$",
    "latitude": 23.1333,
    "longitude": -82.3667,
    "flag": "🇨🇺"
  },
  {
    "code": "CW",
    "iso3": "CUW",
    "name": "Curacao",
    "capital": "Willemstad",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": null,
    "longitude": null,
    "flag": "🇨🇼"
  },
  {
    "code": "CY",
    "iso3": "CYP",
    "name": "Cyprus",
    "capital": "Nicosia",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 35.1676,
    "longitude": 33.3736,
    "flag": "🇨🇾"
  },
  {
    "code": "CZ",
    "iso3": "CZE",
    "name": "Czechia",
    "capital": "Prague",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "CZK",
    "currencyName": "Czech Koruna",
    "symbol": "Kč",
    "latitude": 50.0878,
    "longitude": 14.4205,
    "flag": "🇨🇿"
  },
  {
    "code": "CD",
    "iso3": "COD",
    "name": "Democratic Republic of the Congo",
    "capital": "Kinshasa",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "CDF",
    "currencyName": "Congolese Franc",
    "symbol": "FC",
    "latitude": -4.325,
    "longitude": 15.3222,
    "flag": "🇨🇩"
  },
  {
    "code": "DK",
    "iso3": "DNK",
    "name": "Denmark",
    "capital": "Copenhagen",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "DKK",
    "currencyName": "Danish Krone",
    "symbol": "kr",
    "latitude": 55.6763,
    "longitude": 12.5681,
    "flag": "🇩🇰"
  },
  {
    "code": "DJ",
    "iso3": "DJI",
    "name": "Djibouti",
    "capital": "Djibouti",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "DJF",
    "currencyName": "Djiboutian Franc",
    "symbol": "Fdj",
    "latitude": 11.5806,
    "longitude": 43.1425,
    "flag": "🇩🇯"
  },
  {
    "code": "DM",
    "iso3": "DMA",
    "name": "Dominica",
    "capital": "Roseau",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "XCD",
    "currencyName": "East Caribbean Dollar",
    "symbol": "$",
    "latitude": 15.2976,
    "longitude": -61.39,
    "flag": "🇩🇲"
  },
  {
    "code": "DO",
    "iso3": "DOM",
    "name": "Dominican Republic",
    "capital": "Santo Domingo",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "DOP",
    "currencyName": "Dominican Peso",
    "symbol": "RD$",
    "latitude": 18.479,
    "longitude": -69.8908,
    "flag": "🇩🇴"
  },
  {
    "code": "EC",
    "iso3": "ECU",
    "name": "Ecuador",
    "capital": "Quito",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": -0.229498,
    "longitude": -78.5243,
    "flag": "🇪🇨"
  },
  {
    "code": "EG",
    "iso3": "EGY",
    "name": "Egypt",
    "capital": "Cairo",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "EGP",
    "currencyName": "Egyptian Pound",
    "symbol": "E£",
    "latitude": 30.0982,
    "longitude": 31.2461,
    "flag": "🇪🇬"
  },
  {
    "code": "SV",
    "iso3": "SLV",
    "name": "El Salvador",
    "capital": "San Salvador",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 13.7034,
    "longitude": -89.2073,
    "flag": "🇸🇻"
  },
  {
    "code": "GQ",
    "iso3": "GNQ",
    "name": "Equatorial Guinea",
    "capital": "Malabo",
    "region": "Sub-Saharan Africa",
    "income": "Upper middle income",
    "currency": "XAF",
    "currencyName": "Central African CFA Franc",
    "symbol": "FCFA",
    "latitude": 3.7523,
    "longitude": 8.7741,
    "flag": "🇬🇶"
  },
  {
    "code": "ER",
    "iso3": "ERI",
    "name": "Eritrea",
    "capital": "Asmara",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "ERN",
    "currencyName": "Eritrean Nakfa",
    "symbol": "Nkf",
    "latitude": 15.3315,
    "longitude": 38.9183,
    "flag": "🇪🇷"
  },
  {
    "code": "EE",
    "iso3": "EST",
    "name": "Estonia",
    "capital": "Tallinn",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 59.4392,
    "longitude": 24.7586,
    "flag": "🇪🇪"
  },
  {
    "code": "SZ",
    "iso3": "SWZ",
    "name": "Eswatini",
    "capital": "Mbabane",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "SZL",
    "currencyName": "Swazi Lilangeni",
    "symbol": "E",
    "latitude": -26.5225,
    "longitude": 31.4659,
    "flag": "🇸🇿"
  },
  {
    "code": "ET",
    "iso3": "ETH",
    "name": "Ethiopia",
    "capital": "Addis Ababa",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "ETB",
    "currencyName": "Ethiopian Birr",
    "symbol": "Br",
    "latitude": 9.02274,
    "longitude": 38.7468,
    "flag": "🇪🇹"
  },
  {
    "code": "FO",
    "iso3": "FRO",
    "name": "Faroe Islands",
    "capital": "Torshavn",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 61.8926,
    "longitude": -6.91181,
    "flag": "🇫🇴"
  },
  {
    "code": "FJ",
    "iso3": "FJI",
    "name": "Fiji",
    "capital": "Suva",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "FJD",
    "currencyName": "Fijian Dollar",
    "symbol": "$",
    "latitude": -18.1149,
    "longitude": 178.399,
    "flag": "🇫🇯"
  },
  {
    "code": "FI",
    "iso3": "FIN",
    "name": "Finland",
    "capital": "Helsinki",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 60.1608,
    "longitude": 24.9525,
    "flag": "🇫🇮"
  },
  {
    "code": "FR",
    "iso3": "FRA",
    "name": "France",
    "capital": "Paris",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 48.8566,
    "longitude": 2.35097,
    "flag": "🇫🇷"
  },
  {
    "code": "PF",
    "iso3": "PYF",
    "name": "French Polynesia",
    "capital": "Papeete",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": -17.535,
    "longitude": -149.57,
    "flag": "🇵🇫"
  },
  {
    "code": "GA",
    "iso3": "GAB",
    "name": "Gabon",
    "capital": "Libreville",
    "region": "Sub-Saharan Africa",
    "income": "Upper middle income",
    "currency": "XAF",
    "currencyName": "Central African CFA Franc",
    "symbol": "FCFA",
    "latitude": 0.38832,
    "longitude": 9.45162,
    "flag": "🇬🇦"
  },
  {
    "code": "GE",
    "iso3": "GEO",
    "name": "Georgia",
    "capital": "Tbilisi",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "GEL",
    "currencyName": "Georgian Lari",
    "symbol": "₾",
    "latitude": 41.71,
    "longitude": 44.793,
    "flag": "🇬🇪"
  },
  {
    "code": "DE",
    "iso3": "DEU",
    "name": "Germany",
    "capital": "Berlin",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 52.5235,
    "longitude": 13.4115,
    "flag": "🇩🇪"
  },
  {
    "code": "GH",
    "iso3": "GHA",
    "name": "Ghana",
    "capital": "Accra",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "GHS",
    "currencyName": "Ghanaian Cedi",
    "symbol": "₵",
    "latitude": 5.57045,
    "longitude": -0.20795,
    "flag": "🇬🇭"
  },
  {
    "code": "GI",
    "iso3": "GIB",
    "name": "Gibraltar",
    "capital": "N/A",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": null,
    "longitude": null,
    "flag": "🇬🇮"
  },
  {
    "code": "GR",
    "iso3": "GRC",
    "name": "Greece",
    "capital": "Athens",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 37.9792,
    "longitude": 23.7166,
    "flag": "🇬🇷"
  },
  {
    "code": "GL",
    "iso3": "GRL",
    "name": "Greenland",
    "capital": "Nuuk",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "DKK",
    "currencyName": "Danish Krone",
    "symbol": "kr",
    "latitude": 64.1836,
    "longitude": -51.7214,
    "flag": "🇬🇱"
  },
  {
    "code": "GD",
    "iso3": "GRD",
    "name": "Grenada",
    "capital": "Saint George's",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "XCD",
    "currencyName": "East Caribbean Dollar",
    "symbol": "$",
    "latitude": 12.0653,
    "longitude": -61.7449,
    "flag": "🇬🇩"
  },
  {
    "code": "GU",
    "iso3": "GUM",
    "name": "Guam",
    "capital": "Agana",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 13.4443,
    "longitude": 144.794,
    "flag": "🇬🇺"
  },
  {
    "code": "GT",
    "iso3": "GTM",
    "name": "Guatemala",
    "capital": "Guatemala City",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "GTQ",
    "currencyName": "Guatemalan Quetzal",
    "symbol": "Q",
    "latitude": 14.6248,
    "longitude": -90.5328,
    "flag": "🇬🇹"
  },
  {
    "code": "GN",
    "iso3": "GIN",
    "name": "Guinea",
    "capital": "Conakry",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "GNF",
    "currencyName": "Guinean Franc",
    "symbol": "FG",
    "latitude": 9.51667,
    "longitude": -13.7,
    "flag": "🇬🇳"
  },
  {
    "code": "GW",
    "iso3": "GNB",
    "name": "Guinea-Bissau",
    "capital": "Bissau",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 11.8037,
    "longitude": -15.1804,
    "flag": "🇬🇼"
  },
  {
    "code": "GY",
    "iso3": "GUY",
    "name": "Guyana",
    "capital": "Georgetown",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "GYD",
    "currencyName": "Guyanese Dollar",
    "symbol": "$",
    "latitude": 6.80461,
    "longitude": -58.1548,
    "flag": "🇬🇾"
  },
  {
    "code": "HT",
    "iso3": "HTI",
    "name": "Haiti",
    "capital": "Port-au-Prince",
    "region": "Latin America & Caribbean",
    "income": "Lower middle income",
    "currency": "HTG",
    "currencyName": "Haitian Gourde",
    "symbol": "G",
    "latitude": 18.5392,
    "longitude": -72.3288,
    "flag": "🇭🇹"
  },
  {
    "code": "HN",
    "iso3": "HND",
    "name": "Honduras",
    "capital": "Tegucigalpa",
    "region": "Latin America & Caribbean",
    "income": "Lower middle income",
    "currency": "HNL",
    "currencyName": "Honduran Lempira",
    "symbol": "L",
    "latitude": 15.1333,
    "longitude": -87.4667,
    "flag": "🇭🇳"
  },
  {
    "code": "HK",
    "iso3": "HKG",
    "name": "Hong Kong SAR, China",
    "capital": "N/A",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "HKD",
    "currencyName": "Hong Kong Dollar",
    "symbol": "HK$",
    "latitude": 22.3964,
    "longitude": 114.109,
    "flag": "🇭🇰"
  },
  {
    "code": "HU",
    "iso3": "HUN",
    "name": "Hungary",
    "capital": "Budapest",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "HUF",
    "currencyName": "Hungarian Forint",
    "symbol": "Ft",
    "latitude": 47.4984,
    "longitude": 19.0408,
    "flag": "🇭🇺"
  },
  {
    "code": "IS",
    "iso3": "ISL",
    "name": "Iceland",
    "capital": "Reykjavik",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "ISK",
    "currencyName": "Icelandic Króna",
    "symbol": "kr",
    "latitude": 64.1353,
    "longitude": -21.8952,
    "flag": "🇮🇸"
  },
  {
    "code": "IN",
    "iso3": "IND",
    "name": "India",
    "capital": "New Delhi",
    "region": "South Asia",
    "income": "Lower middle income",
    "currency": "INR",
    "currencyName": "Indian Rupee",
    "symbol": "₹",
    "latitude": 28.6353,
    "longitude": 77.225,
    "flag": "🇮🇳"
  },
  {
    "code": "ID",
    "iso3": "IDN",
    "name": "Indonesia",
    "capital": "Jakarta",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "IDR",
    "currencyName": "Indonesian Rupiah",
    "symbol": "Rp",
    "latitude": -6.19752,
    "longitude": 106.83,
    "flag": "🇮🇩"
  },
  {
    "code": "IR",
    "iso3": "IRN",
    "name": "Iran",
    "capital": "Tehran",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Upper middle income",
    "currency": "IRR",
    "currencyName": "Iranian Rial",
    "symbol": "﷼",
    "latitude": 35.6878,
    "longitude": 51.4447,
    "flag": "🇮🇷"
  },
  {
    "code": "IQ",
    "iso3": "IRQ",
    "name": "Iraq",
    "capital": "Baghdad",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Upper middle income",
    "currency": "IQD",
    "currencyName": "Iraqi Dinar",
    "symbol": "ع.د",
    "latitude": 33.3302,
    "longitude": 44.394,
    "flag": "🇮🇶"
  },
  {
    "code": "IE",
    "iso3": "IRL",
    "name": "Ireland",
    "capital": "Dublin",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 53.3441,
    "longitude": -6.26749,
    "flag": "🇮🇪"
  },
  {
    "code": "IM",
    "iso3": "IMN",
    "name": "Isle of Man",
    "capital": "Douglas",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 54.1509,
    "longitude": -4.47928,
    "flag": "🇮🇲"
  },
  {
    "code": "IL",
    "iso3": "ISR",
    "name": "Israel",
    "capital": "N/A",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "ILS",
    "currencyName": "Israeli New Shekel",
    "symbol": "₪",
    "latitude": 31.7717,
    "longitude": 35.2035,
    "flag": "🇮🇱"
  },
  {
    "code": "IT",
    "iso3": "ITA",
    "name": "Italy",
    "capital": "Rome",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 41.8955,
    "longitude": 12.4823,
    "flag": "🇮🇹"
  },
  {
    "code": "JM",
    "iso3": "JAM",
    "name": "Jamaica",
    "capital": "Kingston",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "JMD",
    "currencyName": "Jamaican Dollar",
    "symbol": "J$",
    "latitude": 17.9927,
    "longitude": -76.792,
    "flag": "🇯🇲"
  },
  {
    "code": "JP",
    "iso3": "JPN",
    "name": "Japan",
    "capital": "Tokyo",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "JPY",
    "currencyName": "Japanese Yen",
    "symbol": "¥",
    "latitude": 35.67,
    "longitude": 139.77,
    "flag": "🇯🇵"
  },
  {
    "code": "JO",
    "iso3": "JOR",
    "name": "Jordan",
    "capital": "Amman",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Upper middle income",
    "currency": "JOD",
    "currencyName": "Jordanian Dinar",
    "symbol": "JD",
    "latitude": 31.9497,
    "longitude": 35.9263,
    "flag": "🇯🇴"
  },
  {
    "code": "KZ",
    "iso3": "KAZ",
    "name": "Kazakhstan",
    "capital": "Astana",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "KZT",
    "currencyName": "Kazakhstani Tenge",
    "symbol": "₸",
    "latitude": 51.1879,
    "longitude": 71.4382,
    "flag": "🇰🇿"
  },
  {
    "code": "KE",
    "iso3": "KEN",
    "name": "Kenya",
    "capital": "Nairobi",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "KES",
    "currencyName": "Kenyan Shilling",
    "symbol": "KSh",
    "latitude": -1.27975,
    "longitude": 36.8126,
    "flag": "🇰🇪"
  },
  {
    "code": "KI",
    "iso3": "KIR",
    "name": "Kiribati",
    "capital": "Tarawa",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "AUD",
    "currencyName": "Australian Dollar",
    "symbol": "$",
    "latitude": 1.32905,
    "longitude": 172.979,
    "flag": "🇰🇮"
  },
  {
    "code": "KP",
    "iso3": "PRK",
    "name": "Korea, Dem. People's Rep.",
    "capital": "Pyongyang",
    "region": "East Asia & Pacific",
    "income": "Low income",
    "currency": "KPW",
    "currencyName": "North Korean Won",
    "symbol": "₩",
    "latitude": 39.0319,
    "longitude": 125.754,
    "flag": "🇰🇵"
  },
  {
    "code": "XK",
    "iso3": "XKX",
    "name": "Kosovo",
    "capital": "Pristina",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 42.565,
    "longitude": 20.926,
    "flag": "🇽🇰"
  },
  {
    "code": "KW",
    "iso3": "KWT",
    "name": "Kuwait",
    "capital": "Kuwait City",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "KWD",
    "currencyName": "Kuwaiti Dinar",
    "symbol": "KD",
    "latitude": 29.3721,
    "longitude": 47.9824,
    "flag": "🇰🇼"
  },
  {
    "code": "KG",
    "iso3": "KGZ",
    "name": "Kyrgyzstan",
    "capital": "Bishkek",
    "region": "Europe & Central Asia",
    "income": "Lower middle income",
    "currency": "KGS",
    "currencyName": "Kyrgyzstani Som",
    "symbol": "сом",
    "latitude": 42.8851,
    "longitude": 74.6057,
    "flag": "🇰🇬"
  },
  {
    "code": "LA",
    "iso3": "LAO",
    "name": "Laos",
    "capital": "Vientiane",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "LAK",
    "currencyName": "Lao Kip",
    "symbol": "₭",
    "latitude": 18.5826,
    "longitude": 102.177,
    "flag": "🇱🇦"
  },
  {
    "code": "LV",
    "iso3": "LVA",
    "name": "Latvia",
    "capital": "Riga",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 56.9465,
    "longitude": 24.1048,
    "flag": "🇱🇻"
  },
  {
    "code": "LB",
    "iso3": "LBN",
    "name": "Lebanon",
    "capital": "Beirut",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "LBP",
    "currencyName": "Lebanese Pound",
    "symbol": "L£",
    "latitude": 33.8872,
    "longitude": 35.5134,
    "flag": "🇱🇧"
  },
  {
    "code": "LS",
    "iso3": "LSO",
    "name": "Lesotho",
    "capital": "Maseru",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "LSL",
    "currencyName": "Lesotho Loti",
    "symbol": "L",
    "latitude": -29.5208,
    "longitude": 27.7167,
    "flag": "🇱🇸"
  },
  {
    "code": "LR",
    "iso3": "LBR",
    "name": "Liberia",
    "capital": "Monrovia",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "LRD",
    "currencyName": "Liberian Dollar",
    "symbol": "$",
    "latitude": 6.30039,
    "longitude": -10.7957,
    "flag": "🇱🇷"
  },
  {
    "code": "LY",
    "iso3": "LBY",
    "name": "Libya",
    "capital": "Tripoli",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Upper middle income",
    "currency": "LYD",
    "currencyName": "Libyan Dinar",
    "symbol": "LD",
    "latitude": 32.8578,
    "longitude": 13.1072,
    "flag": "🇱🇾"
  },
  {
    "code": "LI",
    "iso3": "LIE",
    "name": "Liechtenstein",
    "capital": "Vaduz",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "CHF",
    "currencyName": "Swiss Franc",
    "symbol": "CHF",
    "latitude": 47.1411,
    "longitude": 9.52148,
    "flag": "🇱🇮"
  },
  {
    "code": "LT",
    "iso3": "LTU",
    "name": "Lithuania",
    "capital": "Vilnius",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 54.6896,
    "longitude": 25.2799,
    "flag": "🇱🇹"
  },
  {
    "code": "LU",
    "iso3": "LUX",
    "name": "Luxembourg",
    "capital": "Luxembourg",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 49.61,
    "longitude": 6.1296,
    "flag": "🇱🇺"
  },
  {
    "code": "MO",
    "iso3": "MAC",
    "name": "Macao SAR, China",
    "capital": "N/A",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "MOP",
    "currencyName": "Macanese Pataca",
    "symbol": "MOP$",
    "latitude": 22.1667,
    "longitude": 113.55,
    "flag": "🇲🇴"
  },
  {
    "code": "MG",
    "iso3": "MDG",
    "name": "Madagascar",
    "capital": "Antananarivo",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "MGA",
    "currencyName": "Malagasy Ariary",
    "symbol": "Ar",
    "latitude": -20.4667,
    "longitude": 45.7167,
    "flag": "🇲🇬"
  },
  {
    "code": "MW",
    "iso3": "MWI",
    "name": "Malawi",
    "capital": "Lilongwe",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "MWK",
    "currencyName": "Malawian Kwacha",
    "symbol": "MK",
    "latitude": -13.9899,
    "longitude": 33.7703,
    "flag": "🇲🇼"
  },
  {
    "code": "MY",
    "iso3": "MYS",
    "name": "Malaysia",
    "capital": "Kuala Lumpur",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "MYR",
    "currencyName": "Malaysian Ringgit",
    "symbol": "RM",
    "latitude": 3.12433,
    "longitude": 101.684,
    "flag": "🇲🇾"
  },
  {
    "code": "MV",
    "iso3": "MDV",
    "name": "Maldives",
    "capital": "Male",
    "region": "South Asia",
    "income": "Upper middle income",
    "currency": "MVR",
    "currencyName": "Maldivian Rufiyaa",
    "symbol": "Rf",
    "latitude": 4.1742,
    "longitude": 73.5109,
    "flag": "🇲🇻"
  },
  {
    "code": "ML",
    "iso3": "MLI",
    "name": "Mali",
    "capital": "Bamako",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 13.5667,
    "longitude": -7.50034,
    "flag": "🇲🇱"
  },
  {
    "code": "MT",
    "iso3": "MLT",
    "name": "Malta",
    "capital": "Valletta",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 35.9042,
    "longitude": 14.5189,
    "flag": "🇲🇹"
  },
  {
    "code": "MH",
    "iso3": "MHL",
    "name": "Marshall Islands",
    "capital": "Majuro",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 7.11046,
    "longitude": 171.135,
    "flag": "🇲🇭"
  },
  {
    "code": "MR",
    "iso3": "MRT",
    "name": "Mauritania",
    "capital": "Nouakchott",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "MRU",
    "currencyName": "Mauritanian Ouguiya",
    "symbol": "UM",
    "latitude": 18.2367,
    "longitude": -15.9824,
    "flag": "🇲🇷"
  },
  {
    "code": "MU",
    "iso3": "MUS",
    "name": "Mauritius",
    "capital": "Port Louis",
    "region": "Sub-Saharan Africa",
    "income": "Upper middle income",
    "currency": "MUR",
    "currencyName": "Mauritian Rupee",
    "symbol": "₨",
    "latitude": -20.1605,
    "longitude": 57.4977,
    "flag": "🇲🇺"
  },
  {
    "code": "MX",
    "iso3": "MEX",
    "name": "Mexico",
    "capital": "Mexico City",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "MXN",
    "currencyName": "Mexican Peso",
    "symbol": "$",
    "latitude": 19.427,
    "longitude": -99.1276,
    "flag": "🇲🇽"
  },
  {
    "code": "FM",
    "iso3": "FSM",
    "name": "Micronesia",
    "capital": "Palikir",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 6.91771,
    "longitude": 158.185,
    "flag": "🇫🇲"
  },
  {
    "code": "MD",
    "iso3": "MDA",
    "name": "Moldova",
    "capital": "Chisinau",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "MDL",
    "currencyName": "Moldovan Leu",
    "symbol": "L",
    "latitude": 47.0167,
    "longitude": 28.8497,
    "flag": "🇲🇩"
  },
  {
    "code": "MC",
    "iso3": "MCO",
    "name": "Monaco",
    "capital": "Monaco",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 43.7325,
    "longitude": 7.41891,
    "flag": "🇲🇨"
  },
  {
    "code": "MN",
    "iso3": "MNG",
    "name": "Mongolia",
    "capital": "Ulaanbaatar",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "MNT",
    "currencyName": "Mongolian Tögrög",
    "symbol": "₮",
    "latitude": 47.9129,
    "longitude": 106.937,
    "flag": "🇲🇳"
  },
  {
    "code": "ME",
    "iso3": "MNE",
    "name": "Montenegro",
    "capital": "Podgorica",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 42.4602,
    "longitude": 19.2595,
    "flag": "🇲🇪"
  },
  {
    "code": "MA",
    "iso3": "MAR",
    "name": "Morocco",
    "capital": "Rabat",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "MAD",
    "currencyName": "Moroccan Dirham",
    "symbol": "MAD",
    "latitude": 33.9905,
    "longitude": -6.8704,
    "flag": "🇲🇦"
  },
  {
    "code": "MZ",
    "iso3": "MOZ",
    "name": "Mozambique",
    "capital": "Maputo",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "MZN",
    "currencyName": "Mozambican Metical",
    "symbol": "MT",
    "latitude": -25.9664,
    "longitude": 32.5713,
    "flag": "🇲🇿"
  },
  {
    "code": "MM",
    "iso3": "MMR",
    "name": "Myanmar",
    "capital": "Naypyidaw",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "MMK",
    "currencyName": "Myanmar Kyat",
    "symbol": "Ks",
    "latitude": 21.914,
    "longitude": 95.9562,
    "flag": "🇲🇲"
  },
  {
    "code": "NA",
    "iso3": "NAM",
    "name": "Namibia",
    "capital": "Windhoek",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "NAD",
    "currencyName": "Namibian Dollar",
    "symbol": "$",
    "latitude": -22.5648,
    "longitude": 17.0931,
    "flag": "🇳🇦"
  },
  {
    "code": "NR",
    "iso3": "NRU",
    "name": "Naoero",
    "capital": "Yaren District",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "AUD",
    "currencyName": "Australian Dollar",
    "symbol": "$",
    "latitude": -0.5477,
    "longitude": 166.920867,
    "flag": "🇳🇷"
  },
  {
    "code": "NP",
    "iso3": "NPL",
    "name": "Nepal",
    "capital": "Kathmandu",
    "region": "South Asia",
    "income": "Lower middle income",
    "currency": "NPR",
    "currencyName": "Nepalese Rupee",
    "symbol": "₨",
    "latitude": 27.6939,
    "longitude": 85.3157,
    "flag": "🇳🇵"
  },
  {
    "code": "NL",
    "iso3": "NLD",
    "name": "Netherlands",
    "capital": "Amsterdam",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 52.3738,
    "longitude": 4.89095,
    "flag": "🇳🇱"
  },
  {
    "code": "NC",
    "iso3": "NCL",
    "name": "New Caledonia",
    "capital": "Noum'ea",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": -22.2677,
    "longitude": 166.464,
    "flag": "🇳🇨"
  },
  {
    "code": "NZ",
    "iso3": "NZL",
    "name": "New Zealand",
    "capital": "Wellington",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "NZD",
    "currencyName": "New Zealand Dollar",
    "symbol": "$",
    "latitude": -41.2865,
    "longitude": 174.776,
    "flag": "🇳🇿"
  },
  {
    "code": "NI",
    "iso3": "NIC",
    "name": "Nicaragua",
    "capital": "Managua",
    "region": "Latin America & Caribbean",
    "income": "Lower middle income",
    "currency": "NIO",
    "currencyName": "Nicaraguan Córdoba",
    "symbol": "C$",
    "latitude": 12.1475,
    "longitude": -86.2734,
    "flag": "🇳🇮"
  },
  {
    "code": "NE",
    "iso3": "NER",
    "name": "Niger",
    "capital": "Niamey",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 13.514,
    "longitude": 2.1073,
    "flag": "🇳🇪"
  },
  {
    "code": "NG",
    "iso3": "NGA",
    "name": "Nigeria",
    "capital": "Abuja",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "NGN",
    "currencyName": "Nigerian Naira",
    "symbol": "₦",
    "latitude": 9.05804,
    "longitude": 7.48906,
    "flag": "🇳🇬"
  },
  {
    "code": "MK",
    "iso3": "MKD",
    "name": "North Macedonia",
    "capital": "Skopje",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "MKD",
    "currencyName": "Macedonian Denar",
    "symbol": "ден",
    "latitude": 42.0024,
    "longitude": 21.4361,
    "flag": "🇲🇰"
  },
  {
    "code": "MP",
    "iso3": "MNP",
    "name": "Northern Mariana Islands",
    "capital": "Saipan",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 15.1935,
    "longitude": 145.765,
    "flag": "🇲🇵"
  },
  {
    "code": "NO",
    "iso3": "NOR",
    "name": "Norway",
    "capital": "Oslo",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "NOK",
    "currencyName": "Norwegian Krone",
    "symbol": "kr",
    "latitude": 59.9138,
    "longitude": 10.7387,
    "flag": "🇳🇴"
  },
  {
    "code": "OM",
    "iso3": "OMN",
    "name": "Oman",
    "capital": "Muscat",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "OMR",
    "currencyName": "Omani Rial",
    "symbol": "ر.ع.",
    "latitude": 23.6105,
    "longitude": 58.5874,
    "flag": "🇴🇲"
  },
  {
    "code": "PK",
    "iso3": "PAK",
    "name": "Pakistan",
    "capital": "Islamabad",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "PKR",
    "currencyName": "Pakistani Rupee",
    "symbol": "₨",
    "latitude": 30.5167,
    "longitude": 72.8,
    "flag": "🇵🇰"
  },
  {
    "code": "PW",
    "iso3": "PLW",
    "name": "Palau",
    "capital": "Koror",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 7.34194,
    "longitude": 134.479,
    "flag": "🇵🇼"
  },
  {
    "code": "PA",
    "iso3": "PAN",
    "name": "Panama",
    "capital": "Panama City",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "PAB",
    "currencyName": "Panamanian Balboa",
    "symbol": "B/.",
    "latitude": 8.99427,
    "longitude": -79.5188,
    "flag": "🇵🇦"
  },
  {
    "code": "PG",
    "iso3": "PNG",
    "name": "Papua New Guinea",
    "capital": "Port Moresby",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "PGK",
    "currencyName": "Papua New Guinean Kina",
    "symbol": "K",
    "latitude": -9.47357,
    "longitude": 147.194,
    "flag": "🇵🇬"
  },
  {
    "code": "PY",
    "iso3": "PRY",
    "name": "Paraguay",
    "capital": "Asuncion",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "PYG",
    "currencyName": "Paraguayan Guaraní",
    "symbol": "₲",
    "latitude": -25.3005,
    "longitude": -57.6362,
    "flag": "🇵🇾"
  },
  {
    "code": "PE",
    "iso3": "PER",
    "name": "Peru",
    "capital": "Lima",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "PEN",
    "currencyName": "Peruvian Sol",
    "symbol": "S/.",
    "latitude": -12.0931,
    "longitude": -77.0465,
    "flag": "🇵🇪"
  },
  {
    "code": "PH",
    "iso3": "PHL",
    "name": "Philippines",
    "capital": "Manila",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "PHP",
    "currencyName": "Philippine Peso",
    "symbol": "₱",
    "latitude": 14.5515,
    "longitude": 121.035,
    "flag": "🇵🇭"
  },
  {
    "code": "PL",
    "iso3": "POL",
    "name": "Poland",
    "capital": "Warsaw",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "PLN",
    "currencyName": "Polish Złoty",
    "symbol": "zł",
    "latitude": 52.26,
    "longitude": 21.02,
    "flag": "🇵🇱"
  },
  {
    "code": "PT",
    "iso3": "PRT",
    "name": "Portugal",
    "capital": "Lisbon",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 38.7072,
    "longitude": -9.13552,
    "flag": "🇵🇹"
  },
  {
    "code": "PR",
    "iso3": "PRI",
    "name": "Puerto Rico (US)",
    "capital": "San Juan",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 18.23,
    "longitude": -66.0,
    "flag": "🇵🇷"
  },
  {
    "code": "QA",
    "iso3": "QAT",
    "name": "Qatar",
    "capital": "Doha",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "QAR",
    "currencyName": "Qatari Riyal",
    "symbol": "QR",
    "latitude": 25.2948,
    "longitude": 51.5082,
    "flag": "🇶🇦"
  },
  {
    "code": "CG",
    "iso3": "COG",
    "name": "Republic of the Congo",
    "capital": "Brazzaville",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "XAF",
    "currencyName": "Central African CFA Franc",
    "symbol": "FCFA",
    "latitude": -4.2767,
    "longitude": 15.2662,
    "flag": "🇨🇬"
  },
  {
    "code": "RO",
    "iso3": "ROU",
    "name": "Romania",
    "capital": "Bucharest",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "RON",
    "currencyName": "Romanian Leu",
    "symbol": "lei",
    "latitude": 44.4479,
    "longitude": 26.0979,
    "flag": "🇷🇴"
  },
  {
    "code": "RU",
    "iso3": "RUS",
    "name": "Russia",
    "capital": "Moscow",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "RUB",
    "currencyName": "Russian Ruble",
    "symbol": "₽",
    "latitude": 55.7558,
    "longitude": 37.6176,
    "flag": "🇷🇺"
  },
  {
    "code": "RW",
    "iso3": "RWA",
    "name": "Rwanda",
    "capital": "Kigali",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "RWF",
    "currencyName": "Rwandan Franc",
    "symbol": "FRw",
    "latitude": -1.95325,
    "longitude": 30.0587,
    "flag": "🇷🇼"
  },
  {
    "code": "WS",
    "iso3": "WSM",
    "name": "Samoa",
    "capital": "Apia",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "WST",
    "currencyName": "Samoan Tālā",
    "symbol": "T",
    "latitude": -13.8314,
    "longitude": -171.752,
    "flag": "🇼🇸"
  },
  {
    "code": "SM",
    "iso3": "SMR",
    "name": "San Marino",
    "capital": "San Marino",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 43.9322,
    "longitude": 12.4486,
    "flag": "🇸🇲"
  },
  {
    "code": "ST",
    "iso3": "STP",
    "name": "Sao Tome and Principe",
    "capital": "Sao Tome",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "STN",
    "currencyName": "São Tomé and Príncipe Dobra",
    "symbol": "Db",
    "latitude": 0.20618,
    "longitude": 6.6071,
    "flag": "🇸🇹"
  },
  {
    "code": "SA",
    "iso3": "SAU",
    "name": "Saudi Arabia",
    "capital": "Riyadh",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "SAR",
    "currencyName": "Saudi Riyal",
    "symbol": "SR",
    "latitude": 24.6748,
    "longitude": 46.6977,
    "flag": "🇸🇦"
  },
  {
    "code": "SN",
    "iso3": "SEN",
    "name": "Senegal",
    "capital": "Dakar",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 14.7247,
    "longitude": -17.4734,
    "flag": "🇸🇳"
  },
  {
    "code": "RS",
    "iso3": "SRB",
    "name": "Serbia",
    "capital": "Belgrade",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "RSD",
    "currencyName": "Serbian Dinar",
    "symbol": "din.",
    "latitude": 44.8024,
    "longitude": 20.4656,
    "flag": "🇷🇸"
  },
  {
    "code": "SC",
    "iso3": "SYC",
    "name": "Seychelles",
    "capital": "Victoria",
    "region": "Sub-Saharan Africa",
    "income": "High income",
    "currency": "SCR",
    "currencyName": "Seychellois Rupee",
    "symbol": "SR",
    "latitude": -4.6309,
    "longitude": 55.4466,
    "flag": "🇸🇨"
  },
  {
    "code": "SL",
    "iso3": "SLE",
    "name": "Sierra Leone",
    "capital": "Freetown",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "SLL",
    "currencyName": "Sierra Leonean Leone",
    "symbol": "Le",
    "latitude": 8.4821,
    "longitude": -13.2134,
    "flag": "🇸🇱"
  },
  {
    "code": "SG",
    "iso3": "SGP",
    "name": "Singapore",
    "capital": "Singapore",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "SGD",
    "currencyName": "Singapore Dollar",
    "symbol": "$",
    "latitude": 1.28941,
    "longitude": 103.85,
    "flag": "🇸🇬"
  },
  {
    "code": "SX",
    "iso3": "SXM",
    "name": "Sint Maarten (Dutch part)",
    "capital": "Philipsburg",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": null,
    "longitude": null,
    "flag": "🇸🇽"
  },
  {
    "code": "SK",
    "iso3": "SVK",
    "name": "Slovakia",
    "capital": "Bratislava",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 48.1484,
    "longitude": 17.1073,
    "flag": "🇸🇰"
  },
  {
    "code": "SI",
    "iso3": "SVN",
    "name": "Slovenia",
    "capital": "Ljubljana",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 46.0546,
    "longitude": 14.5044,
    "flag": "🇸🇮"
  },
  {
    "code": "SB",
    "iso3": "SLB",
    "name": "Solomon Islands",
    "capital": "Honiara",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "SBD",
    "currencyName": "Solomon Islands Dollar",
    "symbol": "$",
    "latitude": -9.42676,
    "longitude": 159.949,
    "flag": "🇸🇧"
  },
  {
    "code": "SO",
    "iso3": "SOM",
    "name": "Somalia, Fed. Rep.",
    "capital": "Mogadishu",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "SOS",
    "currencyName": "Somali Shilling",
    "symbol": "Sh.So.",
    "latitude": 2.07515,
    "longitude": 45.3254,
    "flag": "🇸🇴"
  },
  {
    "code": "ZA",
    "iso3": "ZAF",
    "name": "South Africa",
    "capital": "Pretoria",
    "region": "Sub-Saharan Africa",
    "income": "Upper middle income",
    "currency": "ZAR",
    "currencyName": "South African Rand",
    "symbol": "R",
    "latitude": -25.746,
    "longitude": 28.1871,
    "flag": "🇿🇦"
  },
  {
    "code": "KR",
    "iso3": "KOR",
    "name": "South Korea",
    "capital": "Seoul",
    "region": "East Asia & Pacific",
    "income": "High income",
    "currency": "KRW",
    "currencyName": "South Korean Won",
    "symbol": "₩",
    "latitude": 37.5323,
    "longitude": 126.957,
    "flag": "🇰🇷"
  },
  {
    "code": "SS",
    "iso3": "SSD",
    "name": "South Sudan",
    "capital": "Juba",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "SSP",
    "currencyName": "South Sudanese Pound",
    "symbol": "SS£",
    "latitude": 4.85,
    "longitude": 31.6,
    "flag": "🇸🇸"
  },
  {
    "code": "ES",
    "iso3": "ESP",
    "name": "Spain",
    "capital": "Madrid",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "EUR",
    "currencyName": "Euro",
    "symbol": "€",
    "latitude": 40.4167,
    "longitude": -3.70327,
    "flag": "🇪🇸"
  },
  {
    "code": "LK",
    "iso3": "LKA",
    "name": "Sri Lanka",
    "capital": "Colombo",
    "region": "South Asia",
    "income": "Upper middle income",
    "currency": "LKR",
    "currencyName": "Sri Lankan Rupee",
    "symbol": "Rs",
    "latitude": 6.92148,
    "longitude": 79.8528,
    "flag": "🇱🇰"
  },
  {
    "code": "KN",
    "iso3": "KNA",
    "name": "St. Kitts and Nevis",
    "capital": "Basseterre",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "XCD",
    "currencyName": "East Caribbean Dollar",
    "symbol": "$",
    "latitude": 17.3,
    "longitude": -62.7309,
    "flag": "🇰🇳"
  },
  {
    "code": "LC",
    "iso3": "LCA",
    "name": "St. Lucia",
    "capital": "Castries",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "XCD",
    "currencyName": "East Caribbean Dollar",
    "symbol": "$",
    "latitude": 14.0,
    "longitude": -60.9832,
    "flag": "🇱🇨"
  },
  {
    "code": "MF",
    "iso3": "MAF",
    "name": "St. Martin (French part)",
    "capital": "Marigot",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": null,
    "longitude": null,
    "flag": "🇲🇫"
  },
  {
    "code": "VC",
    "iso3": "VCT",
    "name": "St. Vincent and the Grenadines",
    "capital": "Kingstown",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "XCD",
    "currencyName": "East Caribbean Dollar",
    "symbol": "$",
    "latitude": 13.2035,
    "longitude": -61.2653,
    "flag": "🇻🇨"
  },
  {
    "code": "SD",
    "iso3": "SDN",
    "name": "Sudan",
    "capital": "Khartoum",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "SDG",
    "currencyName": "Sudanese Pound",
    "symbol": "SDG",
    "latitude": 15.5932,
    "longitude": 32.5363,
    "flag": "🇸🇩"
  },
  {
    "code": "SR",
    "iso3": "SUR",
    "name": "Suriname",
    "capital": "Paramaribo",
    "region": "Latin America & Caribbean",
    "income": "Upper middle income",
    "currency": "SRD",
    "currencyName": "Surinamese Dollar",
    "symbol": "$",
    "latitude": 5.8232,
    "longitude": -55.1679,
    "flag": "🇸🇷"
  },
  {
    "code": "SE",
    "iso3": "SWE",
    "name": "Sweden",
    "capital": "Stockholm",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "SEK",
    "currencyName": "Swedish Krona",
    "symbol": "kr",
    "latitude": 59.3327,
    "longitude": 18.0645,
    "flag": "🇸🇪"
  },
  {
    "code": "CH",
    "iso3": "CHE",
    "name": "Switzerland",
    "capital": "Bern",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "CHF",
    "currencyName": "Swiss Franc",
    "symbol": "CHF",
    "latitude": 46.948,
    "longitude": 7.44821,
    "flag": "🇨🇭"
  },
  {
    "code": "SY",
    "iso3": "SYR",
    "name": "Syria",
    "capital": "Damascus",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Low income",
    "currency": "SYP",
    "currencyName": "Syrian Pound",
    "symbol": "LS",
    "latitude": 33.5146,
    "longitude": 36.3119,
    "flag": "🇸🇾"
  },
  {
    "code": "TJ",
    "iso3": "TJK",
    "name": "Tajikistan",
    "capital": "Dushanbe",
    "region": "Europe & Central Asia",
    "income": "Lower middle income",
    "currency": "TJS",
    "currencyName": "Tajikistani Somoni",
    "symbol": "SM",
    "latitude": 38.5878,
    "longitude": 68.7864,
    "flag": "🇹🇯"
  },
  {
    "code": "TZ",
    "iso3": "TZA",
    "name": "Tanzania",
    "capital": "Dodoma",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "TZS",
    "currencyName": "Tanzanian Shilling",
    "symbol": "TSh",
    "latitude": -6.17486,
    "longitude": 35.7382,
    "flag": "🇹🇿"
  },
  {
    "code": "TH",
    "iso3": "THA",
    "name": "Thailand",
    "capital": "Bangkok",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "THB",
    "currencyName": "Thai Baht",
    "symbol": "฿",
    "latitude": 13.7308,
    "longitude": 100.521,
    "flag": "🇹🇭"
  },
  {
    "code": "BS",
    "iso3": "BHS",
    "name": "The Bahamas",
    "capital": "Nassau",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "BSD",
    "currencyName": "Bahamian Dollar",
    "symbol": "$",
    "latitude": 25.0661,
    "longitude": -77.339,
    "flag": "🇧🇸"
  },
  {
    "code": "GM",
    "iso3": "GMB",
    "name": "The Gambia",
    "capital": "Banjul",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "GMD",
    "currencyName": "Gambian Dalasi",
    "symbol": "D",
    "latitude": 13.4495,
    "longitude": -16.5885,
    "flag": "🇬🇲"
  },
  {
    "code": "TL",
    "iso3": "TLS",
    "name": "Timor-Leste",
    "capital": "Dili",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": -8.56667,
    "longitude": 125.567,
    "flag": "🇹🇱"
  },
  {
    "code": "TG",
    "iso3": "TGO",
    "name": "Togo",
    "capital": "Lome",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "XOF",
    "currencyName": "West African CFA Franc",
    "symbol": "CFA",
    "latitude": 6.1228,
    "longitude": 1.2255,
    "flag": "🇹🇬"
  },
  {
    "code": "TO",
    "iso3": "TON",
    "name": "Tonga",
    "capital": "Nuku'alofa",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "TOP",
    "currencyName": "Tongan Paʻanga",
    "symbol": "T$",
    "latitude": -21.136,
    "longitude": -175.216,
    "flag": "🇹🇴"
  },
  {
    "code": "TT",
    "iso3": "TTO",
    "name": "Trinidad and Tobago",
    "capital": "Port-of-Spain",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "TTD",
    "currencyName": "Trinidad and Tobago Dollar",
    "symbol": "TT$",
    "latitude": 10.6596,
    "longitude": -61.4789,
    "flag": "🇹🇹"
  },
  {
    "code": "TN",
    "iso3": "TUN",
    "name": "Tunisia",
    "capital": "Tunis",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "TND",
    "currencyName": "Tunisian Dinar",
    "symbol": "DT",
    "latitude": 36.7899,
    "longitude": 10.21,
    "flag": "🇹🇳"
  },
  {
    "code": "TR",
    "iso3": "TUR",
    "name": "Turkey",
    "capital": "Ankara",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "TRY",
    "currencyName": "Turkish Lira",
    "symbol": "₺",
    "latitude": 39.7153,
    "longitude": 32.3606,
    "flag": "🇹🇷"
  },
  {
    "code": "TM",
    "iso3": "TKM",
    "name": "Turkmenistan",
    "capital": "Ashgabat",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "TMT",
    "currencyName": "Turkmenistan Manat",
    "symbol": "T",
    "latitude": 37.9509,
    "longitude": 58.3794,
    "flag": "🇹🇲"
  },
  {
    "code": "TC",
    "iso3": "TCA",
    "name": "Turks and Caicos Islands",
    "capital": "Grand Turk",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 21.4602778,
    "longitude": -71.141389,
    "flag": "🇹🇨"
  },
  {
    "code": "TV",
    "iso3": "TUV",
    "name": "Tuvalu",
    "capital": "Funafuti",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "AUD",
    "currencyName": "Australian Dollar",
    "symbol": "$",
    "latitude": -8.6314877,
    "longitude": 179.089567,
    "flag": "🇹🇻"
  },
  {
    "code": "UG",
    "iso3": "UGA",
    "name": "Uganda",
    "capital": "Kampala",
    "region": "Sub-Saharan Africa",
    "income": "Low income",
    "currency": "UGX",
    "currencyName": "Ugandan Shilling",
    "symbol": "USh",
    "latitude": 0.314269,
    "longitude": 32.5729,
    "flag": "🇺🇬"
  },
  {
    "code": "UA",
    "iso3": "UKR",
    "name": "Ukraine",
    "capital": "Kiev",
    "region": "Europe & Central Asia",
    "income": "Upper middle income",
    "currency": "UAH",
    "currencyName": "Ukrainian Hryvnia",
    "symbol": "₴",
    "latitude": 50.4536,
    "longitude": 30.5038,
    "flag": "🇺🇦"
  },
  {
    "code": "AE",
    "iso3": "ARE",
    "name": "United Arab Emirates",
    "capital": "Abu Dhabi",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "High income",
    "currency": "AED",
    "currencyName": "UAE Dirham",
    "symbol": "AED",
    "latitude": 24.4764,
    "longitude": 54.3705,
    "flag": "🇦🇪"
  },
  {
    "code": "GB",
    "iso3": "GBR",
    "name": "United Kingdom",
    "capital": "London",
    "region": "Europe & Central Asia",
    "income": "High income",
    "currency": "GBP",
    "currencyName": "British Pound",
    "symbol": "£",
    "latitude": 51.5002,
    "longitude": -0.126236,
    "flag": "🇬🇧"
  },
  {
    "code": "US",
    "iso3": "USA",
    "name": "United States",
    "capital": "Washington D.C.",
    "region": "North America",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 38.8895,
    "longitude": -77.032,
    "flag": "🇺🇸"
  },
  {
    "code": "UY",
    "iso3": "URY",
    "name": "Uruguay",
    "capital": "Montevideo",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "UYU",
    "currencyName": "Uruguayan Peso",
    "symbol": "",
    "latitude": -34.8941,
    "longitude": -56.0675,
    "flag": "🇺🇾"
  },
  {
    "code": "UZ",
    "iso3": "UZB",
    "name": "Uzbekistan",
    "capital": "Tashkent",
    "region": "Europe & Central Asia",
    "income": "Lower middle income",
    "currency": "UZS",
    "currencyName": "Uzbekistani Soʻm",
    "symbol": "soʻm",
    "latitude": 41.3052,
    "longitude": 69.269,
    "flag": "🇺🇿"
  },
  {
    "code": "VU",
    "iso3": "VUT",
    "name": "Vanuatu",
    "capital": "Port-Vila",
    "region": "East Asia & Pacific",
    "income": "Lower middle income",
    "currency": "VUV",
    "currencyName": "Vanuatu Vatu",
    "symbol": "VT",
    "latitude": -17.7404,
    "longitude": 168.321,
    "flag": "🇻🇺"
  },
  {
    "code": "VE",
    "iso3": "VEN",
    "name": "Venezuela",
    "capital": "Caracas",
    "region": "Latin America & Caribbean",
    "income": "Lower middle income",
    "currency": "VES",
    "currencyName": "Venezuelan Bolívar",
    "symbol": "Bs.S",
    "latitude": 9.08165,
    "longitude": -69.8371,
    "flag": "🇻🇪"
  },
  {
    "code": "VN",
    "iso3": "VNM",
    "name": "Vietnam",
    "capital": "Hanoi",
    "region": "East Asia & Pacific",
    "income": "Upper middle income",
    "currency": "VND",
    "currencyName": "Vietnamese Đồng",
    "symbol": "₫",
    "latitude": 21.0069,
    "longitude": 105.825,
    "flag": "🇻🇳"
  },
  {
    "code": "VI",
    "iso3": "VIR",
    "name": "Virgin Islands (U.S.)",
    "capital": "Charlotte Amalie",
    "region": "Latin America & Caribbean",
    "income": "High income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": 18.3358,
    "longitude": -64.8963,
    "flag": "🇻🇮"
  },
  {
    "code": "PS",
    "iso3": "PSE",
    "name": "West Bank and Gaza",
    "capital": "N/A",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Lower middle income",
    "currency": "ILS",
    "currencyName": "Israeli Shekel",
    "symbol": "₪",
    "latitude": null,
    "longitude": null,
    "flag": "🇵🇸"
  },
  {
    "code": "YE",
    "iso3": "YEM",
    "name": "Yemen",
    "capital": "Sana'a",
    "region": "Middle East, North Africa, Afghanistan & Pakistan",
    "income": "Low income",
    "currency": "YER",
    "currencyName": "Yemeni Rial",
    "symbol": "﷼",
    "latitude": 15.352,
    "longitude": 44.2075,
    "flag": "🇾🇪"
  },
  {
    "code": "ZM",
    "iso3": "ZMB",
    "name": "Zambia",
    "capital": "Lusaka",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "ZMW",
    "currencyName": "Zambian Kwacha",
    "symbol": "ZK",
    "latitude": -15.3982,
    "longitude": 28.2937,
    "flag": "🇿🇲"
  },
  {
    "code": "ZW",
    "iso3": "ZWE",
    "name": "Zimbabwe",
    "capital": "Harare",
    "region": "Sub-Saharan Africa",
    "income": "Lower middle income",
    "currency": "USD",
    "currencyName": "US Dollar",
    "symbol": "$",
    "latitude": -17.8312,
    "longitude": 31.0672,
    "flag": "🇿🇼"
  }
];
